### ISSUE TITLE
The Wire.requestFrom() should not be follewed by a Wire.endTransmission.

### ISSUE THREAD

**Issue by Koepel** [andrei-tatar/rfm-sensors#1]
In the file "rfm-sensors/sensor-multi/lib/MAX44009/MAX44009.cpp" there is twice a Wire.endTransmission() after a Wire.requestFrom(). Those Wire.endTransmission() is not just a stop and they may not be used for that. They can be removed.

Explanation: [Common-mistakes#2](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#2)

**Comment by andrei-tatar** [comment]
@Koepel Thanks for the info. Only noticed the issue now!
